version: '3'
services:
    nginx:
        image: nginx:latest
        container_name: nginx
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "./api:/var/www/html"
            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        ports:
            - "${NGINX_PORT}:3001"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: ${DO_RESTART}
        depends_on:
            - php
            - db
    php:
        image: nanoninja/php-fpm:${PHP_VERSION}
        restart: ${DO_RESTART}
        container_name: php
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./api:/var/www/html"
    db:
        image: mariadb:${MYSQL_VERSION}
        restart: ${DO_RESTART}
        container_name: db
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "3309:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
            - "./etc/mysql/mycustom.cnf:/etc/mysql/conf.d/custom.cnf"
    composer:
        image: "composer"
        container_name: composer
        volumes:
            - "./api:/app"
        command: install
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: rabbitmq
        environment:
            RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
            RABBITMQ_DEFAULT_USER: "rabbitmq"
            RABBITMQ_DEFAULT_PASS: "rabbitmq"
            RABBITMQ_DEFAULT_VHOST: "/"
        ports:
            - 5672:5672
            - 15672:15672